log_level = "debug"

# [[ignore_subnets]]
# cidr = "128.0.0.0/24"

[[proxy]]
type = "socks5"
ip = "127.0.0.1"
port = 1080
# auth = { UserPassword = { 0 = "username", 1 = "password" } }

# [[proxy]]
# type = "http"
# ip = "127.0.0.1"
# port = 8888
