[package]
name = "proxyc_common"
version = "0.1.0"
authors = ["j3d42 <melvil.guillaume@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
serde_json = "1.0"
thiserror = "1.0"
log = "0.4"
